name: synoapi
description: synoapi
version: 0.1.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  logging: ^1.0.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

dev_dependencies:
  test: ^1.20.0
  build_runner: ^2.0.0
